### ISSUE TITLE
please do one tag 

### ISSUE THREAD

**Issue by sergiomb2** [shlomif/PySol-Extra-Mahjongg-Cardsets#1]
Hello , 
I'm Sérgio, packager of PySolFC on Fedora.
It is possible add to PySolFC-cardsets package ? 
if yes, please Can we have one tag of this sources ? 

Thanks

**Comment by shlomif** [comment]
Hi @sergiomb2 ! Not sure I understand (the grammar is off). Do you want us to do a "git tag" with a release, of this repo so it can be packaged?

**Comment by shlomif** [comment]
Note that https://github.com/shlomif/PySolFC-Cardsets has release tarballs on https://sourceforge.net/projects/pysolfc/files/PySolFC-Cardsets/ .

**Comment by sergiomb2** [comment]
:smile:  Please, do one tag for this PySol-Extra-Mahjongg-Cardsets .
After I may add it to PySolFC-cardsets as a sub-package ? or we have any issue ?

**Comment by shlomif** [comment]
@sergiomb2 : thanks, I tagged it as 0.2.0 for now. Do you need anything else?

**Comment by sergiomb2** [comment]
Fantastic , so it can be added to PySolFC-cardsets as a sub-package ? 
Thanks
